test:
  extends:
    file: docker-compose-common.yml
    service: webapp
  build: .
  command:
    make jenkins
  environment:
    TEST_OUTPUT_PATH: /tmp/jenkins
  volumes:
    - $WORKSPACE:/tmp/jenkins
